version: '3.6'
services:
  dbt:
    image: article1dataops/dbt:latest
    volumes:
      - .:/usr/app
    ports:
      - "8080:8080"
  db:
    container_name: skutopia_postgres
    image: postgres:14.1-alpine
    restart:  always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=worldbank_api_db
    ports:
      - "5440:5440"
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
volumes:
  db:
    driver: local
