name: schedule_dbt_job

on: push

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: worldbank_api_db

jobs:
  schedule_dbt_run:
    name: schedule_dbt_run
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@master

    - uses: actions/setup-python@v1
      with:
        python-version: "3.7.x"

    - name: Install dependencies
      run: |
        pip install dbt-postgres
        dbt deps

    # dbt related commands here - run use --target prod/dev to run for specific environments
    - name: Run dbt models
      run: dbt run

    - name: Test dbt models
      run: dbt test
